gemfile:
  - Gemfile
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-20mode
  - jruby-21mode
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: 1.8.7
    - rvm: 1.9.2
    - rvm: rbx
  fast_finish: true